name: goreleaser

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up go
        uses: actions/setup-go@v2
      -
        name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
